apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "node-app.fullname" . }}-deployment"
  labels:
    app: "{{ include "node-app.name" . }}"
spec:
  replicas: {{ .Values.replicaCount}}
  selector: 
    matchLabels: 
      app:  "{{ include "node-app.name" . }}"
  template: 
    metadata: 
      labels:
        app: node-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.name}}"
          imagePullPolicy: Always
          ports:
          - containerPort: 8080   
