
replicaCount: 2

image:
  name: mark80/node-app
  repository: mark80/node-app
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name:

podSecurityContext: {}

securityContext: {}


service:
  type: NodePort
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: node-app.local
      paths: []
  tls: []


resources: {}


nodeSelector: {}

tolerations: []

affinity: {}
